config/routes.rb
Rails.application.routes.draw do
  resources :nationalities
  resources :student_scholarships
  resources :scholarships
  resources :user_sessions
  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  get 'main' => 'users#main', :as => :main

  resources :users
  resources :student_entries
  get 'paso' => 'student_entries#paso', :as => :paso

  resources :student_academics
  resources :student_courses
  resources :courses
  resources :activities
  resources :academics
  resources :students
  get "students/show_photo/:id" => "students#show_photo"
  post 'students/activate/:id' => 'students#activate' #, :as => :activate
  root 'students#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/scholarship.rb
class Scholarship < ApplicationRecord
end

app/controllers/scholarships_controller.rb
class ScholarshipsController < ApplicationController
  before_action :set_scholarship, only: [:show, :edit, :update, :destroy]

  # GET /scholarships
  # GET /scholarships.json
  def index
    @scholarships = Scholarship.all
  end

  # GET /scholarships/1
  # GET /scholarships/1.json
  def show
  end

  # GET /scholarships/new
  def new
    @scholarship = Scholarship.new
  end

  # GET /scholarships/1/edit
  def edit
  end

  # POST /scholarships
  # POST /scholarships.json
  def create
    @scholarship = Scholarship.new(scholarship_params)

    respond_to do |format|
      if @scholarship.save
        format.html { redirect_to @scholarship, notice: 'Scholarship was successfully created.' }
        format.json { render :show, status: :created, location: @scholarship }
      else
        format.html { render :new }
        format.json { render json: @scholarship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scholarships/1
  # PATCH/PUT /scholarships/1.json
  def update
    respond_to do |format|
      if @scholarship.update(scholarship_params)
        format.html { redirect_to @scholarship, notice: 'Scholarship was successfully updated.' }
        format.json { render :show, status: :ok, location: @scholarship }
      else
        format.html { render :edit }
        format.json { render json: @scholarship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scholarships/1
  # DELETE /scholarships/1.json
  def destroy
    @scholarship.destroy
    respond_to do |format|
      format.html { redirect_to scholarships_url, notice: 'Scholarship was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scholarship
      @scholarship = Scholarship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scholarship_params
      params.require(:scholarship).permit(:name)
    end
end

app/helpers/scholarships_helper.rb
module ScholarshipsHelper
end

app/views/scholarships/_form.html.erb
<%= form_with(model: scholarship, local: true) do |form| %>
  <% if scholarship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(scholarship.errors.count, "error") %> prohibited this scholarship from being saved:</h2>

      <ul>
      <% scholarship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :scholarship_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/scholarships/edit.html.erb
<h1>Editing Scholarship</h1>

<%= render 'form', scholarship: @scholarship %>

<%= link_to 'Show', @scholarship %> |
<%= link_to 'Back', scholarships_path %>

app/views/scholarships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Scholarships</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scholarships.each do |scholarship| %>
      <tr>
        <td><%= scholarship.name %></td>
        <td><%= link_to 'Show', scholarship %></td>
        <td><%= link_to 'Edit', edit_scholarship_path(scholarship) %></td>
        <td><%= link_to 'Destroy', scholarship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Scholarship', new_scholarship_path %>

app/views/scholarships/new.html.erb
<h1>New Scholarship</h1>

<%= render 'form', scholarship: @scholarship %>

<%= link_to 'Back', scholarships_path %>

app/views/scholarships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @scholarship.name %>
</p>

<%= link_to 'Edit', edit_scholarship_path(@scholarship) %> |
<%= link_to 'Back', scholarships_path %>