config/routes.rb
Rails.application.routes.draw do
  resources :nationalities
  resources :student_scholarships
  resources :scholarships
  resources :user_sessions
  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  get 'main' => 'users#main', :as => :main

  resources :users
  resources :student_entries
  get 'paso' => 'student_entries#paso', :as => :paso

  resources :student_academics
  resources :student_courses
  resources :courses
  resources :activities
  resources :academics
  resources :students
  get "students/show_photo/:id" => "students#show_photo"
  post 'students/activate/:id' => 'students#activate' #, :as => :activate
  root 'students#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/nationality.rb
class Nationality < ApplicationRecord
end

app/controllers/nationalities_controller.rb
class NationalitiesController < ApplicationController
  before_action :set_nationality, only: [:show, :edit, :update, :destroy]

  # GET /nationalities
  # GET /nationalities.json
  def index
    @nationalities = Nationality.all
  end

  # GET /nationalities/1
  # GET /nationalities/1.json
  def show
  end

  # GET /nationalities/new
  def new
    @nationality = Nationality.new
  end

  # GET /nationalities/1/edit
  def edit
  end

  # POST /nationalities
  # POST /nationalities.json
  def create
    @nationality = Nationality.new(nationality_params)

    respond_to do |format|
      if @nationality.save
        format.html { redirect_to @nationality, notice: 'Nationality was successfully created.' }
        format.json { render :show, status: :created, location: @nationality }
      else
        format.html { render :new }
        format.json { render json: @nationality.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nationalities/1
  # PATCH/PUT /nationalities/1.json
  def update
    respond_to do |format|
      if @nationality.update(nationality_params)
        format.html { redirect_to @nationality, notice: 'Nationality was successfully updated.' }
        format.json { render :show, status: :ok, location: @nationality }
      else
        format.html { render :edit }
        format.json { render json: @nationality.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nationalities/1
  # DELETE /nationalities/1.json
  def destroy
    @nationality.destroy
    respond_to do |format|
      format.html { redirect_to nationalities_url, notice: 'Nationality was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nationality
      @nationality = Nationality.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def nationality_params
      params.require(:nationality).permit(:id, :name, :country, :iso2)
    end
end

app/helpers/nationalities_helper.rb
module NationalitiesHelper
end

app/views/nationalities/_form.html.erb
<%= form_with(model: nationality, local: true) do |form| %>
  <% if nationality.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(nationality.errors.count, "error") %> prohibited this nationality from being saved:</h2>

      <ul>
      <% nationality.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :id %>
    <%= form.number_field :id, id: :nationality_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :nationality_name %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country, id: :nationality_country %>
  </div>

  <div class="field">
    <%= form.label :iso2 %>
    <%= form.text_field :iso2, id: :nationality_iso2 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/nationalities/edit.html.erb
<h1>Editing Nationality</h1>

<%= render 'form', nationality: @nationality %>

<%= link_to 'Show', @nationality %> |
<%= link_to 'Back', nationalities_path %>

app/views/nationalities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Nationalities</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Country</th>
      <th>Iso2</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @nationalities.each do |nationality| %>
      <tr>
        <td><%= nationality.id %></td>
        <td><%= nationality.name %></td>
        <td><%= nationality.country %></td>
        <td><%= nationality.iso2 %></td>
        <td><%= link_to 'Show', nationality %></td>
        <td><%= link_to 'Edit', edit_nationality_path(nationality) %></td>
        <td><%= link_to 'Destroy', nationality, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Nationality', new_nationality_path %>

app/views/nationalities/new.html.erb
<h1>New Nationality</h1>

<%= render 'form', nationality: @nationality %>

<%= link_to 'Back', nationalities_path %>

app/views/nationalities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @nationality.id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @nationality.name %>
</p>

<p>
  <strong>Country:</strong>
  <%= @nationality.country %>
</p>

<p>
  <strong>Iso2:</strong>
  <%= @nationality.iso2 %>
</p>

<%= link_to 'Edit', edit_nationality_path(@nationality) %> |
<%= link_to 'Back', nationalities_path %>